# Generated by Django 5.0.1 on 2024-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transcription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=100)),
                ("source_title", models.CharField(max_length=255)),
                ("source_owner", models.CharField(max_length=100)),
                ("transcription", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
